export const createUserManagerResources = (resources: any) => ({
    ManageUsers: {
        UserSearch: resources.UsersManagement.UsersSearch,
        RemoveAccessDisclaimer: resources.UsersManagement.PageMemberRevokeAccessTitle,
        RemoveAccess: resources.UsersManagement.MemberRevokeAccess,
        Close:resources.MetaResource.Close,
        Profile: resources.UsersManagement.Profile,
        EmailLabel:resources.UsersManagement.AccessRequestProfileEmail,
        FirstnameLabel:resources.UsersManagement.AccessRequestProfileFname,
        LastnameLabel: resources.UsersManagement.AccessRequestProfileLname,
        JobLabel:resources.UsersManagement.AccessRequestProfileJobTitle,
        CityLabel:resources.UsersManagement.AccessRequestProfileCity,
        ViewProfile: resources.UsersManagement.AccessRequestSeeProfile,
        Members: resources.UsersManagement.MembersTitle,
        UserSelected: resources.ManageUsers.UserSelected,
        PendingSelected: resources.ManageUsers.PendingSelected,
        Name:resources.UsersManagement.MembersName,
        Role: resources.UsersManagement.MembersRole,
        DomainSaved: resources.UsersManagement.DomainsUpdateSuccess,
        ErrorWrongDomain: resources.UsersManagement.DomainsAddInvalid,
        ErrorUsedDomain: resources.UsersManagement.DomainAddAlreadyInList,
        DomainDescription: resources.UsersManagement.PageMemberAccessSpeech,
        DomainPlaceholder: resources.UsersManagement.ModalDomainInputText,
        Add: resources.UsersManagement.ModalDomainAddButton,
        Save: resources.UsersManagement.ModalDomainSaveButton,
        EmailDescription: resources.UsersManagement.PageMemberInvitationsSpeech,
        EmailPlaceholder: resources.UsersManagement.ModalInvitationInputText,
        ErrorInvalidMail:resources.UsersManagement.AddMailInvalid,
        ErrorEmailUsed: resources.ManageUsers.ErrorEmailUsed,
        ErrorMailInvited:resources.ManageUsers.ErrorMailInvited,
        SendInvitations:resources.UsersManagement.ModalInvitationSendButton,
        NumbersOfLines: resources.UsersManagement.UserListRowsLabel,
        Pagination: resources.ManageUsers.Pagination,
        PendingInvitations: resources.UsersManagement.PageMemberMenuPendingInvitations,
        ResendInvitations: resources.UsersManagement.PendingInvitationsResendSelected,
        DeleteInvitations: resources.UsersManagement.PendingInvitationsRemoveSelected,
        ResendInvitation: resources.UsersManagement.PendingInvitationResend,
        DeleteInvitation:resources.UsersManagement.DeleteInvitation,
        ListOfRequests: resources.UsersManagement.AccessRequestTitle,
        RequestSelected: resources.ManageUsers.RequestSelected,
        AcceptAllRequests:resources.UsersManagement.AccessRequestAcceptSelected,
        DenyAllRequest: resources.UsersManagement.AccessRequestRejectSelected,
        LastName:resources.UsersManagement.AccessRequestName,
        Accept: resources.UsersManagement.AccessRequestAllow,
        Refuse: resources.UsersManagement.AccessRequestDeny,
        Invitations: resources.UsersManagement.PageMemberInvitationsTitle,
        InvitationsDescription: resources.UsersManagement.PageMemberInvitationsSpeech,
        InvitationsAction: resources.UsersManagement.PageMemberInvitationsInviteButton,
        Authorize: resources.UsersManagement.PageMemberAccessTitle,
        AuthorizeDescription: resources.UsersManagement.PageMemberAccessSpeech,
        AuthorizeAction: resources.UsersManagement.PageMemberAccessSetupButton,
        InvitationsSuccess: resources.UsersManagement.ModalInvitationSuccessScreenTitle,
        InvitationsSuccessDescription: resources.UsersManagement.ModalInvitationSuccessScreenSpeech,
        Ok: resources.UsersManagement.ModalInvitationSuccessScreenOkButton,
        AccessRemovedSuccess:resources.UsersManagement.RemoveSuccess,
        UpdateRoleSuccess: resources.UsersManagement.UserRoleChanged,
        ResendInvitationSuccess: resources.UsersManagement.InvitationResendSuccess,
        RemoveInvitationSuccess: resources.UsersManagement.InvitationRemoveSuccess,
        RefuseRequestSuccess: resources.UsersManagement.RequestDeleteSuccess,
        AcceptRequestSuccess: resources.UsersManagement.RequestAllowedSuccess,
        Cancel: resources.MetaResource.Cancel,
        RequestForAccess: resources.UsersManagement.PageMemberMenuAccessRequests,
        SelectRole: resources.UsersManagement.SelectRole
    }
   
})