export const {
  API_URL,
  BIMOBJECT_API_URL,
  SSO_URL,
  API_URL_DICTIONARIES,
  METABASE_SITE_URL,
  METABASE_ASYNC_LOGS_DASHBOARD_ID,
  EN_ONLINE_HELP_URL,
  FR_ONLINE_HELP_URL,
  ONFLY_HTTP_PROTOCOL,
  ONFLY_DOMAIN,
} = TARGET_ENV;
